# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 7f4f301
_src_path: https://github.com/PratikBhusal-Copier-Templates/java.git
copyright_holder: Pratik Bhusal
copyright_license: ISC
java_app_or_library: java
project_artifact_id: hello-world
project_artifact_id_package_name_suffix: hello.world
project_description: &#39;&#39;
project_group_id: org.example
project_name: Hello World
project_version: 1.0-SNAPSHOT
